apiVersion: 1

datasources:
  - name: LeetCode Tracker PostgreSQL
    type: postgres
    uid: leetcode-tracker-postgres
    access: proxy
    url: db:5432
    database: leetcode_tracker
    user: leetcode_user
    secureJsonData:
      password: leetcode_password
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
      database: leetcode_tracker
    isDefault: true
    editable: true
